#!/usr/bin/env python3
"""Maintainer tool: build the offline, cross-platform official ACP SDK bundle."""

import argparse
import hashlib
import json
import pathlib
import shutil
import subprocess
import tempfile
import zipfile


PACKAGES = {
    "agent-client-protocol": "0.11.0",
    "pydantic": "2.13.4",
    "pydantic-core": "2.46.4",
    "annotated-types": "0.8.0",
    "typing-extensions": "4.16.0",
    "typing-inspection": "0.4.2",
}
PURE_REQUIREMENTS = tuple(
    "%s==%s" % (name, version)
    for name, version in PACKAGES.items()
    if name != "pydantic-core"
)
PYTHON_MINORS = ("310", "311", "312", "313", "314")
PLATFORMS = {
    "macos-arm64": "aarch64-apple-darwin",
    "macos-x86_64": "x86_64-apple-darwin",
    "linux-gnu-arm64": "aarch64-unknown-linux-gnu",
    "linux-gnu-x86_64": "x86_64-unknown-linux-gnu",
    "linux-musl-arm64": "aarch64-unknown-linux-musl",
    "linux-musl-x86_64": "x86_64-unknown-linux-musl",
}
NOTICE = """# Bundled ACP Runtime Notices

This directory is generated by `scripts/build_acp_runtime_bundle.py` and is shipped so installed
Agent Swarm skills do not install or download Python packages at runtime.

The archives contain unmodified distributions of:

- agent-client-protocol 0.11.0 (MIT)
- Pydantic 2.13.4 and pydantic-core 2.46.4 (MIT)
- annotated-types 0.8.0 (MIT)
- typing-extensions 4.16.0 (PSF-2.0)
- typing-inspection 0.4.2 (MIT)

The corresponding distribution metadata and full license files are retained inside `pure.zip` and
each native archive. Agent Swarm does not copy or regenerate ACP schemas; it imports the official
SDK distribution from this bundle.
"""


def _run_uv(target, requirements, *, python_version, python_platform):
    subprocess.run(
        [
            "uv",
            "pip",
            "install",
            "--target",
            str(target),
            "--python-version",
            python_version,
            "--python-platform",
            python_platform,
            "--only-binary",
            ":all:",
            "--no-deps",
            *requirements,
        ],
        check=True,
    )


def _archive(source, destination):
    with zipfile.ZipFile(
        destination,
        "w",
        compression=zipfile.ZIP_DEFLATED,
        compresslevel=9,
    ) as archive:
        for path in sorted(source.rglob("*")):
            if (
                not path.is_file()
                or "__pycache__" in path.parts
                or path.name == ".lock"
            ):
                continue
            relative = path.relative_to(source).as_posix()
            info = zipfile.ZipInfo(relative, date_time=(1980, 1, 1, 0, 0, 0))
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = (path.stat().st_mode & 0xFFFF) << 16
            archive.writestr(info, path.read_bytes(), compresslevel=9)


def _sha256(path):
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def build(output):
    if output.exists():
        raise RuntimeError("bundle output already exists: %s" % output)
    output.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix="agent-swarm-acp-bundle-") as temporary:
        work = pathlib.Path(temporary)
        staged = work / "output"
        native_output = staged / "native"
        native_output.mkdir(parents=True)

        pure_target = work / "pure"
        _run_uv(
            pure_target,
            PURE_REQUIREMENTS,
            python_version="3.10",
            python_platform="x86_64-unknown-linux-gnu",
        )
        pure_archive = staged / "pure.zip"
        _archive(pure_target, pure_archive)

        native = {}
        for python_minor in PYTHON_MINORS:
            python_version = "%s.%s" % (python_minor[0], python_minor[1:])
            for platform_key, uv_platform in PLATFORMS.items():
                key = "cp%s-%s" % (python_minor, platform_key)
                native_target = work / key
                _run_uv(
                    native_target,
                    ("pydantic-core==%s" % PACKAGES["pydantic-core"],),
                    python_version=python_version,
                    python_platform=uv_platform,
                )
                archive_path = native_output / (key + ".zip")
                _archive(native_target, archive_path)
                native[key] = {
                    "file": archive_path.relative_to(staged).as_posix(),
                    "sha256": _sha256(archive_path),
                }

        manifest = {
            "schema_version": 1,
            "python": {"minimum": "3.10", "maximum": "3.14"},
            "packages": PACKAGES,
            "pure": {"file": "pure.zip", "sha256": _sha256(pure_archive)},
            "native": native,
        }
        (staged / "manifest.json").write_text(
            json.dumps(manifest, indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )
        (staged / "NOTICE.md").write_text(NOTICE, encoding="utf-8")
        shutil.move(str(staged), str(output))


def main(argv=None):
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--output",
        default=str(pathlib.Path(__file__).resolve().parents[1] / "assets" / "acp-runtime"),
    )
    args = parser.parse_args(argv)
    build(pathlib.Path(args.output).resolve())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
